# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TwitterDataTool' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for TwitterDataTool
pod 'TwitterKit', '~> 3.4'
pod "CloudTagView"

end
